#!/usr/bin/env bash
#This is a while loop to write Best School 10 times with bad luck at 4 and good luck at 8
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
		
	i=$((i +1))
done
