#!/usr/bin/env bash
# This script write "To infinity and beyond" forever and writes "I am invincible!!" when receiving a SIGTERM

echo $$ > /var/run/myscript.pid
i=0
while [ $i -lt 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" ; rm -rf  /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm -rf /var/run/holbertonscript.pid; exit' SIGQUIT
done
