#!/usr/bin/env bash
# This script write "To infinity and beyond" forever and writes "I am invincible!!" when receiving a SIGTERM

i=0
while [ $i -lt 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
